version: '2'
services:
    orgcontrol-app:
        image: orgcontrol
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://orgcontrol-mariadb:3306/orgcontrol
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    orgcontrol-mariadb:
        extends:
            file: mariadb.yml
            service: orgcontrol-mariadb
